# -*- coding: utf-8 -*-

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrFTSsjBexZR5vAhSbtLmCk7OqT46jdD
"""

'''Roll No: AU2040188
   Name:Barodia Purvansh Tejasbhai '''

   
#1. Write a Python program to read and print your name
name=input("Enter your Name: ")
print(name)

'''
Enter your Name: Barodia Purvansh
Barodia Purvansh

'''

#2. Write a Python program to print your ID – Card
name=input("Enter your Name: ")
rollNo= input("Enter Your Rollno: ")
print("Name:",name)
print("Rollno:",rollNo)

'''
Enter your Name: Barodia Purvansh
Enter Your Rollno: 188
Name: Barodia Purvansh
Rollno: 188

'''

#3. input a number and check whether the entered number is even or odd.
num=int(input("Enter Number: "))
if num%2==0:
  print(num,"is even Numnber.")
else:
  print(num,"is odd Number.")

'''
Enter Number: 450
450 is even Numnber.

'''
#4. check whether a number is divisible by 5 or not.
num=int(input("Enter Number: "))
if num%5==0:
  print(num,"is divisible by 5")
else:
  print(num,"is not divisible by 5")

'''
Enter Number: 224
224 is not divisible by 5

'''
#5. read a month number and print corresponding month name.
N=int(input("Enter month (1 to 12): "))
if N==1:
      print("January")
elif N==2:
      print("Febaruary")
elif N==3:
      print("March")
elif N==4:
      print("April")
elif N==5:
      print("May")
elif N==6:
      print("June")
elif N==7:
      print("July")
elif N==8:
      print("Augest")
elif N==9:
      print("September")
elif N==10:
      print("October")
elif N==11:
      print("November")
elif N==12:
      print("December")
else:
      print("invalid Input")

'''
Enter month (1 to 12): 3
March

'''
#6. find the Square Root of a given number
A=float(input("Enter numer:"))
S=A**0.5
print(S,"is square root of",A)

'''
Enter numer:64
8.0 is square root of 64.0

'''
#7. input angles of a triangle and check whether triangle is valid or not
angle1=float(input("Enter 1st angle of triangle: "))
angle2=float(input("Enter 2nd angle of triangle: "))
angle3=float(input("Enter 3rd angle of triangle: "))

sum= angle1 +angle2 +angle3
if sum==180:
  print("It is a valid triangle")
else:
  print("It is a valid triangle")

'''
Enter 1st angle of triangle: 50
Enter 2nd angle of triangle: 60
Enter 3rd angle of triangle: 70
It is a valid triangle

'''
#8. calculate the Area of a Triangle.
base=float(input("Enter base for tringle :"))
hight=float(input("Enter height for triangle : "))
area=(base*hight)/2
print("Area of given triangle is",area)

'''
Enter base for tringle :6
Enter height for triangle : 9
Area of given triangle is 27.0

'''
#9. check whether a person is eligible to vote or not.
Age=int(input("Enter your Age :"))
Nationa=input("Enter Your Nationality: ")
Nation=Nationa.title()

if Age>=18 and Nation=='India' :
             print("you are eligible to vote")
else:
             print("you are not eligible to vote") 
'''
Enter your Age :19
Enter Your Nationality: india
you are eligible to vote

'''
#10. Generate and print a Random Number
import random
Random_number=random.random()
print(Random_number,"is a Random Number")

'''
0.30089487414858307 is a Random Number

'''
#11. Convert Celsius to Fahrenheit.
celsius=float(input("Enter Temperature in Celsius: "))
fahrenheit=(celsius*(9/5))+32
print("Temperature in Fahrenheit is",fahrenheit)

'''
Enter Temperature in Celsius: 0
Temperature in Fahrenheit is 32.0

'''
#12. make a Simple Calculator.
I = 'Yes'
while (I == 'Yes' or I == 'yes' or I == 'YES'):
    A=float(input("Enter Num 1: "))
    B=float(input("Enter Num 2: "))
    N=int(input("Chosse any one primary computing: 1.addition 2.subtraction 3.multiplication 4.division : "))
    if N==1:
        print("Sum is:", A+B)
    elif N==2:
        print("subtraction is", A-B)
    elif N==3:
        print("Mul is:", A*B)
    elif N==4:
       print("Divison is: ", A/B)
    else:
        print ("Invalid Number(enter a number from 1 to 4)")
    I=input("Do you want to continue?: ")
print ("Bye!!.. Have a good day! ")

'''
Enter Num 1: 256
Enter Num 2: 598
Chosse any one primary computing: 1.addition 2.subtraction 3.multiplication 4.division : 3
Mul is: 153088.0
Do you want to continue?: no
Bye!!.. Have a good day! 

'''
#13. sum of first 10 numbers
sum=0
i=1
for i in range(1,11):
    sum=sum+i
    i+=1
print("Sum of first 10 numbers is",sum)

'''
Sum of first 10 numbers is 55

'''
#14. input 3 numbers from user and print the maximum among them
A=float(input("Enter Number 1 "))
B=float(input("Enter Number 2 "))
C=float(input("enter Number 3 "))
if A>B and A>C:
    print(A,"is grater than ",B,"and",C)
elif B>A and B>C:
    print(B,"is grater than ",A,"and",C)
else:
    print(C,"is grater than ",A,"and",B)

'''
Enter Number 1 25
Enter Number 2 20
enter Number 3 65
65.0 is grater than  25.0 and 20.0

'''
#15. sum of odd numbers and even numbers from 1 to N
N=int(input("Enter Number: "))
sum=0
if N%2==0:
  for i in range(2,N+1,2):
      sum=sum+i
  print("Sum of even Numbers from 1 to", N ,"is",sum)
else:
  for i in range(1,N+1,2):
    sum=sum+i
  print ("Sum of odd Numbers from 1 to", N ,"is",sum)

'''
Enter Number: 100
Sum of even Numbers from 1 to 100 is 2550

'''
#16. convert a distance in meters to feet and inches
#    Conversion formula:
#    1 feet = meters * 3.281
#    1 Feet = 12 inch 
distance=float(input("Enter Distance in meters: "))
feet=distance * 3.281
inch=feet *12
print("Distance in feet is",feet)
print("Distance in inch is",inch)

'''
Enter Distance in meters: 1
Distance in feet is 3.281
Distance in inch is 39.372

'''
#17. read a character from the user and check whether it is a vowel or consonant
N=input("Enter a character :")
N=N.upper()
X=['A','E','I','O','U']
if N in X:
  print("It is a vowle character")
else:
  print("It is a consonat character")

'''
Enter a character :P
It is a consonat character

'''
#18. check whether a character is uppercase or lowercase alphabet
chr=input("Enter a Character: ")
if chr.isupper():
  print(chr,"is in Uppercase alphabet")
else:
  print(chr,"is in lowercase alphabet")

'''
Enter a Character: p
p is in lowercase alphabet  

'''
#19. accept two numbers and one mathematical operator. Calculate and display appropriate answer.
n1=float(input("Enter Number1: "))
operator=input("Enter a vaild mathematical operator(+,-,*,/):  ")
n2=float(input("Enter Number2: "))
if operator=='+':
  print(n1+n2)
elif operator=='-':
  print(n1-n2)
elif operator=='*':
  print(n1*n2)
elif operator=='/':
  print('n1/n2')
else:
  print("Invaild Input")

'''
Enter Number1: 25
Enter a vaild mathematical operator(+,-,*,/):  +
Enter Number2: 85
110.0

'''
#20. enter a number from the user and display the sum of all the digits in the number
n=int(input("Enter a number:"))
sum=0
while n>0 :
  m=n%10
  sum=sum+m
  n=n//10
print(sum,end=" ")

'''
Enter a number:15486
24 

'''
#21. Accept a year from the user and check whether it is leap year or not.
year=int(input("Enter year: "))
if year%100==0:
  if year%400==0:
      print(year,"is a leap year")
  else:
    print(year,"is not a leap year")
elif year%4==0:
  print(year,"is a leap year")

'''
Enter year: 1300
1300 is not a leap year

'''
#22. ExtractDigits to extract each digit from an int in the reverse order
n=int(input("Enter Number: "))
while(n>0):
  m=n%10
  print(m,end=" ")
  n=n//10

'''
Enter Number: 123456789
9 8 7 6 5 4 3 2 1 

'''
#23. Accept a number N from the user and print the first N elements of the Fibonacci series
N=int(input("Enter how many element of the fibonacci series you want?(grater than 2): "))
if N<=2:
  print("invalid input")
print("Fibonacci series:")
print("0 1",end=" ")
i=0
X=0
Y=1
while(i<N-2):
   Z= X + Y
   print(Z,end=" ")
   X=Y
   Y=Z
   i+=1

'''
Enter how many element of the fibonacci series you want?(grater than 2): 9
Fibonacci series:
0 1 1 2 3 5 8 13 21 

'''
#24. Calculate the area of triangle given its three sides
a=float(input("Enter length of 1st side: "))
b=float(input("Enter length of 2nd side: "))
c=float(input("Enter length of 3rd side: "))
s=a+b+c/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
area=int(area)
print("Area of tringle is",area)

'''
Enter length of 1st side: 10.26
Enter length of 2nd side: 25
Enter length of 3rd side: 12.3
Area of tringle is 784

'''
#25. Write a program that take input of 3 subjects marks out of 150. Count the percentage. Print
#    the Grade/Class based on conditions:
phy=float(input("Enter Marks of Physics: "))
mat=float(input("Enter Marks of Maths: "))
che=float(input("Enter Marks of Chemistry: "))
per=round((phy*mat*che*100)/150)
if (per>=70):
  print("DISTINCTION")
elif (60<per<69):
  print("FIRST CLASS")
elif (50<per<59):
  print("SECOND CLASS")
elif (40<per<49):
  print("PASS CLASS")
else:
  print("FAIL")

'''
Enter Marks of Physics: 49
Enter Marks of Maths: 38
Enter Marks of Chemistry: 34
DISTINCTION

'''
#26. Accept the marks (out of 70) for 3 subjects (Maths, physics, chemistry) from the user and
#    check if the student is eligible for admission based on the following criteria:
#    i) Mathematics >= 50%, Physics >= 45%, Chemistry >= 60%, and Overall Percentage >= 65%
#    OR
#    ii) Total marks of Mathematics + Physics >= 120

phy=float(input("Enter Marks of Physics: "))
mat=float(input("Enter Marks of Maths: "))
che=float(input("Enter Marks of Chemistry: "))
per_m=(mat*100)/70
per_p=(phy*100)/70
per_c=(che*100)/70
per=(phy*mat*che*100)/210

if ((per_m>=50 and per_p>=45 and per_c>=60 and per>=65) or ((mat+phy)>=120)):
  print("You are eligible for admission")
else:
  print("You are not eligible for admission")

'''
Enter Marks of Physics: 59
Enter Marks of Maths: 62
Enter Marks of Chemistry: 66
You are eligible for admission

'''
#27. Considering three numbers provided by the user as length of sides of a triangle, first check, if
#    the values are valid for representing the sides of a triangle (i.e. whether a triangle can be
#    drawn using the given values). If the lengths of sides are valid, print the type of the triangle.

a=float(input("Enter length of 1st side: "))
b=float(input("Enter length of 2nd side: "))
c=float(input("Enter length of 3rd side: "))
if (a<=0 or b<=0 or c<=0):
  print("Length can't be Zero or Negative Number")
elif (a<b+c and b<a+c and c<a+b):
   if (a==b and b==c):
     print("It is a Equilateral Triangle")
   elif (a==c or b==c or a==c):
     print("It is a Isosceles Tringle")
   else:
     print("It is a Scalene Tringle")
else:
  print("It is not a Triangle")

'''
Enter length of 1st side: 3
Enter length of 2nd side: 4
Enter length of 3rd side: 6
It is a Scalene Tringle

'''
#28. Write to program to print following series using looping concept (use while or for loop).
#    A. 1, 2, 3, 4 ........ 100
#    B. 100, 99, 98.......1
#    C. 1, 3, 5, 7........99
#    D. 2, 4, 8, 16, 32, 64

#=====>A
for i in range(1,101):
  print(i,end=" ")

#=====>B
for i in range(100,0,-1):
  print(i,end=" ")

#=====>C
for i in range(1,100,2):
  print(i,end=" ")

#=====>D
i=2
while(i<=64):
  print(i, end=" ")
  i=i*2


#29. Write a program to print following pattern. (hint: nested for loop)
#    A
#    B B
#    C C C
#    D D D D

N=int(input("Enter numbers of row you want in output: "))
for i in range(0,N+1):
  M=64+i
  C=chr(M)
  for j in range(N-i,N):
    print(C,end=" ")
  print()

'''
Enter numbers of row you want in output: 5

A 
B B 
C C C 
D D D D 
E E E E E 

'''
#30. Print multiplication table of a number entered by the user. Validate that the number must be between 1 and 20.
N=int(input("Enter Which Number of table you want?(input should be 1-20): "))     #it means 1 and 20 are Excluded
if (1<=N or N>=20) :
  print("It is invalid Number")
for i in range(1,11):
  print(N,"X",i,"=",N*i)

'''Enter Which Number of table you want?(input should be 1-20): 5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50
'''
